- name: PROVISION VPC SUBNETS & F5 INSTANCES
  # https://docs.ansible.com/ansible/latest/modules/bigip_appsvcs_extension_module.html#bigip-appsvcs-extension-module
  # https://docs.ansible.com/ansible/latest/modules/uri_module.html#uri-module
  # search for: Create a JIRA issue
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/big_creds.yaml
  vars:
    uri_method: POST

  tasks:
    # highlight block and indent with: Cmd-]
    - name: Issue AS3 declaration
      uri:
        url: https://108.128.216.12/mgmt/shared/appsvcs/declare
        user: "{{ bigip_user }}"
        password: "{{ bigip_pass }}"
        method: "{{ uri_method }}"
        # body: "{{ lookup('file','./as3-declarations/simple-as3.json') }}"
        body: "{{ lookup('file','./as3-declarations/serviceMain_disabled.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no