- name: PROVISION VPC SUBNETS & F5 INSTANCES
  # https://docs.ansible.com/ansible/latest/modules/bigip_appsvcs_extension_module.html#bigip-appsvcs-extension-module
  # https://docs.ansible.com/ansible/latest/modules/uri_module.html#uri-module
  # search for: Create a JIRA issue
  hosts: localhost
  connection: local
  gather_facts: no

  - name: Create a JIRA issue
    uri:
      url: https://your.jira.example.com/rest/api/2/issue/
      user: your_username
      password: your_pass
      method: POST
      body: "{{ lookup('file','issue.json') }}"
      force_basic_auth: yes
      status_code: 201
      body_format: json